#!/bin/sh
############################################################
#
# Program history
############################################################
# Created by. Daejeon Office
# 2022.03.18 Version : Park Si Hyung, Yoon Jun Su
#

############################################################
#
# Program variables
############################################################
# Configuration file path
TBIS_AUTO_LOGFILE="tbis.log"
TBIS_AUTO_CFGFILE="tbis.cfg"
TBIS_AUTO_SQLFILE="tbis.sql"
TBIS_CWD_PATH=`pwd`
############################################################
#
# Function lists
############################################################
FN_AUTO_LOGFILE(){
    TBIS_AUTO_TIME=`date +%F_%T |sed 's/://g' |sed 's/-//g'`
    if [ -f $TBIS_AUTO_LOGFILE ]
    then
        mv $TBIS_AUTO_LOGFILE "$TBIS_AUTO_LOGFILE"_"$TBIS_AUTO_TIME"
    fi
}

FN_AUTO_PROGRESS_CHECK(){
    echo
    if [ $INSTALL_MODE == "ALL" ]
    then
        YESNO=YES
    else
        printf "continue ? ( [Y]es / [N]o / [S]kip ) : "
        read INPUT_YESNO
        case $INPUT_YESNO in
            "YES"|"Yes"|"yes"|"y"|"Y")
                YESNO=YES;;
            "NO"|"No"|"no"|"n"|"N")
                exit;;
            "SKIP"|"Skip"|"S"|"s")
                YESNO=SKIP;;
        esac
        echo
    fi
    
}

FN_AUTO_ENGINE(){    
    # Engine install
    if [ $TIBERO_ENGINE == "Y" ] || [ $TIBERO_ENGINE == "y" ]
    then
        echo
        echo "############################################################"
        echo "# tbis Progress> Engine"
        echo "############################################################"
        echo
        echo "tar -xvzf ../binary/tibero*.tar.gz -C $USER_HOME"
        echo
        FN_AUTO_PROGRESS_CHECK
        if [ $YESNO == "YES" ]
        then
            tar -xvzf ../binary/tibero*.tar.gz -C $USER_HOME
        fi     
    fi
    
}

FN_AUTO_TBINARY(){
    if [ $TIBERO_TBINARY == "Y" ] || [ $TIBERO_TBINARY == "y" ]
    then
        echo
        echo "############################################################"
        echo "# tbis Progress> tbinary"
        echo "############################################################"
        echo
        echo "tar -xvf ../binary/tbinary*.tar -C $USER_HOME"
        echo
        FN_AUTO_PROGRESS_CHECK
        if [ $YESNO == "YES" ]
        then
            tar -xvf ../binary/tbinary*.tar -C $USER_HOME
        fi  
    fi
}

FN_AUTO_PROFILE(){
    echo
    echo "############################################################"
    echo "# tbis Progress> Profile " 
    echo "############################################################"
    echo
    FN_AUTO_PROGRESS_CHECK
    if [ $YESNO == "YES" ]
    then
        TIBERO_BASHPROFILE=$USER_HOME/.bash_profile
        TIBERO_PROFILE=$USER_HOME/.profile
        if [ -f $TIBERO_PROFILE ]
        then   
            sh tbis.cfg USER_PROFILE >> $USER_HOME/.profile
        elif [ -f $TIBERO_BASHPROFILE ]
        then
            sh tbis.cfg USER_PROFILE >> $USER_HOME/.bash_profile
        fi
    fi
}

FN_AUTO_LICENSE(){
    if [ -z $TIBERO_LICENSE ]
    then
        echo
        echo "# tbis message>../binary/license.xml file"
        echo
        exit
    else
        echo
        echo "############################################################"
        echo "# tbis Progress> license "    
        echo "############################################################"
        echo
        echo "cp ../binary/license.xml $TB_HOME/license/license.xml"
        echo
        FN_AUTO_PROGRESS_CHECK
        if [ $YESNO == "YES" ]
        then
            cp ../binary/license.xml $TB_HOME/license/license.xml   
        fi
        
    fi
}

FN_AUTO_TB_SID_TIP(){
    echo
    echo "############################################################"
    echo "# tbis Progress> TB_SID TIP File"
    echo "############################################################"
    echo
    echo "sh tbis.cfg TB_SID_TIP > $TB_HOME/config/$TB_SID.tip"
    echo
    FN_AUTO_PROGRESS_CHECK        
    if [ $YESNO == "YES" ]
    then
        if [ $TIBERO_NODE == "observer" ]
        then
            2>/dev/null
        else
            sh tbis.cfg TB_SID_TIP > $TB_HOME/config/$TB_SID.tip        
        fi
    fi
}

FN_AUTO_CM_SID_TIP(){
    echo
    echo "############################################################"
    echo "# tbis Progress> CM_SID TIP File"
    echo "############################################################"
    echo
    echo "sh tbis.cfg CM_SID_TIP > $TB_HOME/config/$TIBERO_NODE.tip"
    echo
    FN_AUTO_PROGRESS_CHECK
    if [ $YESNO == "YES" ]
    then
        if [ $TIBERO_TYPE == "SINGLE" ]
        then
            echo "SINGLE"
        else
            sh tbis.cfg CM_SID_TIP > $TB_HOME/config/$TIBERO_NODE.tip
        fi
    fi
}

FN_AUTO_TBDSN(){
    echo
    echo "############################################################"
    echo "# tbis Progress> TBDSN"
    echo "############################################################"
    echo
    echo "sh tbis.cfg FN_TB_DSN > $TB_HOME/client/cofnig/tbdsn.tbr"
    echo
    FN_AUTO_PROGRESS_CHECK
    if [ $YESNO == "YES" ]
    then
        sh tbis.cfg TB_DSN > $TB_HOME/client/config/tbdsn.tbr
    fi
}

FN_AUTO_SINGLE(){
    export TB_SID=`echo $DB_NAME`
}

FN_AUTO_TSC(){
    if [ $TIBERO_NODE == "primary" ] 
    then
        export TB_SID=`echo "$DB_NAME"_p`
    elif [ $TIBERO_NODE == "standby" ]
    then
        export TB_SID=`echo "$DB_NAME"_s`
    elif [ $TIBERO_NODE == "observer" ]
    then
        export TB_SID="Observer Not TB_SID"
    fi
}

FN_AUTO_TAC(){
    if [ $TIBERO_NODE == "cm0" ]
    then
        export TB_SID=`echo "$DB_NAME"0`
    elif [ $TIBERO_NODE == "cm1" ]
    then
        export TB_SID=`echo "$DB_NAME"1`
    fi
}

FN_AUTO_CM_RESOURCE(){
    echo
    echo "############################################################"
    echo "# tbis Progress> tbcm resource "    
    echo "############################################################"
    echo
    sh tbis.cfg CM_RESOURCE
    echo
    FN_AUTO_PROGRESS_CHECK
    if [ $YESNO == "YES" ]
    then
        if [ $TIBERO_TYPE == "TSC" ]
        then
            if [ $TIBERO_NODE == "primary" ]
            then
                echo
                if [ -z $NODE1_VIP_ETH ]
                then
                    su - $USER_NAME -c "cmrctl add network --name net0 --ipaddr $NODE1_INTER_IP --portno 29000"
                    su - $USER_NAME -c "cmrctl add cluster --name cls0 --incnet net0 --cfile $TB_HOME/config/CMFILE_cls0"
                    su - $USER_NAME -c "cmrctl start cluster --name cls0"
                    su - $USER_NAME -c "cmrctl add service --name $DB_NAME --cname cls0 --tscid 11 --obsip $NODE2_INTER_IP --obsport 9050"
                    su - $USER_NAME -c "cmrctl add db --name $TB_SID --svcname $DB_NAME --dbhome $TB_HOME --envfile $USER_HOME/.bash_profile"
                fi
            elif [ $TIBERO_NODE == "standby" ]
            then
                    su - $USER_NAME -c "cmrctl add network --name net1 --ipaddr $NODE2_INTER_IP --portno 29000"
                    su - $USER_NAME -c "cmrctl add cluster --name cls1 --incnet net1 --cfile $TB_HOME/config/CMFILE_cls1"
                    su - $USER_NAME -c "cmrctl start cluster --name cls1"
                    su - $USER_NAME -c "cmrctl add service --name $DB_NAME --cname cls1 --tscid 11 --obsip $NODE2_INTER_IP --obsport 9050"
                    su - $USER_NAME -c "cmrctl add db --name $TB_SID --svcname $DB_NAME --dbhome $TB_HOME --envfile $USER_HOME/.bash_profile"
            elif [ $TIBERO_NODE == "observer" ]
            then
                2>/dev/null
            fi
        elif [ $TIBERO_TYPE == "TAC" ]
        then
            echo
            if [ $TIBERO_NODE == "cm0" ]
            then
                echo
            elif [ $TIBERO_NODE == "cm1" ]
            then
                echo
            fi
        fi
    fi
}

FN_AUTO_CM_BOOT(){
    echo
    echo "############################################################"
    echo "# tbis Progress> tbcm boot "    
    echo "############################################################"
    echo
    FN_AUTO_PROGRESS_CHECK
    echo
    if [ $YESNO == "YES" ]
    then
        if [ $TIBERO_NODE == "observer" ]
        then
            su - $USER_NAME -c "tbcmobs -b"
        else
            if [ -z $NODE1_VIP_ETH ]
            then
                su - $USER_NAME -c "tbcm -b"
            elif [ -n $NODE1_VIP_ETH ]
            then
                tbcm -b
                echo "VIP"
            fi
        fi
    fi
}

FN_AUTO_CHANGE_OWNER(){
    # Owner Change Files
    echo "############################################################"
    echo "#  tbis Progress> Change Owner"
    echo "############################################################"
    echo
    echo "chwon -R $USER_NAME:$GROUP_NAME $USER_HOME"
    echo
    FN_AUTO_PROGRESS_CHECK
    if [ $YESNO == "YES" ]
    then
        chown -R $USER_NAME:$GROUP_NAME $USER_HOME
    fi
    
}

FN_AUTO_TB_BOOT(){
    echo "############################################################"
    echo "#  tbis Progress> tbboot"
    echo "############################################################"
    echo
    echo "su - $USER_NAME -c \"tbboot $TB_BOOT_OPTION\""
    echo
    TB_BOOT_OPTION=$1

    FN_AUTO_PROGRESS_CHECK
    if [ $YESNO == "YES" ]
    then
        TIBERO_PROCESS=`ps -ef |grep tbsvr |grep -v grep`
        if [ -z $TIBERO_PROCESS ]
        then
            su - $USER_NAME -c "tbboot $TB_BOOT_OPTION"
            echo
            echo
            sleep 1 
        else
            ps -ef |grep tbsvr |grep -v grep
        fi
    fi
}

FN_AUTO_CREATEDB(){
    echo "############################################################"
    echo "#  tbis Progress> CREATE DATABASE"
    echo "############################################################"
    echo
    echo "@$TBIS_CWD_PATH/tbis.sql"
    echo
    FN_AUTO_PROGRESS_CHECK
    echo
    if [ $YESNO == "YES" ]
    then    
        su - $USER_NAME -c "
            tbsql -s sys/tibero <<EOF
            @$TBIS_CWD_PATH/tbis.sql
            exit
            EOF
        "
        echo
        echo
        sleep 1
    fi
}

FN_AUTO_SYSTEM_SHELL(){
    echo "############################################################"
    echo "#  tbis Progress> system.sh"
    echo "############################################################"
    echo
    echo "su - tibero_tbis -c \"sh $TB_HOME/scripts/system.sh -p1 tibero -p2 syscat -a1 Y -a2 Y -a3 Y -a4 Y\""
    echo
    FN_AUTO_PROGRESS_CHECK
    echo
    if [ $YESNO == "YES" ]
    then    
        su - tibero_tbis -c "sh $TB_HOME/scripts/system.sh -p1 tibero -p2 syscat -a1 Y -a2 Y -a3 Y -a4 Y"
        echo
        echo
        sleep 1
    fi    
}

FN_AUTO_INSTALL_CHECK(){
    clear
    . ./tbis.cfg

    TIBERO_LICENSE=`cat ../binary/license.xml |grep license |head -n 1 `
    echo "[*] TIBERO Auto installation Tools Configuration Checking STEP"
    echo "-----------------------------------------------------------------"
    echo "# System Check"
    echo "- OS USER : $USER_NAME"
    echo "- OS USER GROUP : $GROUP_NAME"
    echo "- OS HOME : $USER_HOME"
    echo "-----------------------------------------------------------------"
    echo "# TIBERO Binary"
    if [ -n $TIBERO_ENGINE ]
    then
        echo "- Engine PATH : $TB_HOME"
    fi  

    if [ -n $TIBERO_TBINARY ]
    then
        echo "- tbinary PATH : $TB_HOME/tbinary"
    fi
    echo "-----------------------------------------------------------------"
    echo "# TIBERO DATABASE"
    if [ $TIBERO_TYPE == "SINGLE" ]
    then
        echo "- TYPE : SINGLE"
        FN_AUTO_SINGLE
    elif [ $TIBERO_TYPE == "TSC" ]
    then
        echo "- TYPE : TSC"
        echo "- NODE : $TIBERO_NODE"
        FN_AUTO_TSC
    elif [ $TIBERO_TYPE == "TAC" ]
    then
        echo "- TYPE : TAC"
        echo "- NODE : $TIBERO_NODE"
        FN_AUTO_TAC
    fi

    echo "- TB_SID : $TB_SID"
    echo "- CM_SID : $TIBERO_NODE"
    echo "- CHARACTER SET : `cat tbis.sql|grep CHARACTER |awk '{print $NF}'`"
    echo "-----------------------------------------------------------------"
    echo "# TIBERO Configuration Files"
    echo "- cat tbis.cfg : TIBERO Total Configuration File"
    echo "- cat tbis.sql : CREATE DATABASE SQL File"
    echo "-----------------------------------------------------------------"
    
    ### IN PROCESS
    echo
    printf "continue ? ( [Y]es / [N]o / [AA] All Auto] ) : "
    read INPUT_YESNO
    case $INPUT_YESNO in
        "YES"|"Yes"|"yes"|"y"|"Y")
            INSTALL_MODE=YES;;
        "NO"|"No"|"no"|"n"|"N")
            exit;;
        "AA"|"aa")
            INSTALL_MODE=ALL;;
    esac
    echo
    ###

    if [ -z $USER_HOME  ]
    then
        echo " tbis message> User home checking "
        exit
    fi
}

FN_AUTO_TB_DOWN(){
    echo "############################################################"
    echo "#  tbis Progress> tbdown"
    echo "############################################################"
    echo
    echo "su - $USER_NAME -c \"tbdown $TB_DOWN_OPTION\""
    echo
    TB_DOWN_OPTION=$1
    su - $USER_NAME -c "tbdown $TB_DOWN_OPTION"
}

FN_AUTO_TSC_COPY(){
    echo "############################################################"
    echo "#  tbis Progress> DF COPY to Target node"
    echo "############################################################"
    echo
    echo "scp -r $CONTROL_FILE_PATH1/tbctl1 "$USER_NAME"@"$NODE2_INTER_IP":$CONTROL_FILE_PATH1/tbctl1"
    echo "scp -r $CONTROL_FILE_PATH2/tbctl2 "$USER_NAME"@"$NODE2_INTER_IP":$CONTROL_FILE_PATH2/tbctl2"
    echo "scp -r $DB_CREATE_FILE_DEST/tbdata "$USER_NAME"@"$NODE2_INTER_IP":$DB_CREATE_FILE_DEST/tbdata"
    echo "scp -r $LOG_ARCHIVE_DEST/tbarch "$USER_NAME"@"$NODE2_INTER_IP":$LOG_ARCHIVE_DEST/tbarch"
    echo
    FN_AUTO_PROGRESS_CHECK
    echo
    if [ $YESNO == "YES" ]
    then  
        scp -P $SFTP_PORT -r $CONTROL_FILE_PATH1/tbctl1 "$USER_NAME"@"$NODE2_INTER_IP":$CONTROL_FILE_PATH1/tbctl1
        scp -P $SFTP_PORT -r $CONTROL_FILE_PATH2/tbctl2 "$USER_NAME"@"$NODE2_INTER_IP":$CONTROL_FILE_PATH2/tbctl2
        scp -P $SFTP_PORT -r $DB_CREATE_FILE_DEST/tbdata "$USER_NAME"@"$NODE2_INTER_IP":$DB_CREATE_FILE_DEST/tbdata
        scp -P $SFTP_PORT -r $LOG_ARCHIVE_DEST/tbarch "$USER_NAME"@"$NODE2_INTER_IP":$LOG_ARCHIVE_DEST/tbarch
    fi    
}
FN_AUTO_TSC_CFG(){
    echo "############################################################"
    echo "#  tbis Progress> Target TSC Configuration"
    echo "############################################################"
    echo
    echo "ALTER DATABASE STANDBY CONTROLFILE;"
    echo
    FN_AUTO_PROGRESS_CHECK
    echo
    if [ $YESNO == "YES" ]
    then   
        su - $USER_NAME -c "
            tbsql -s sys/tibero <<EOF
            ALTER DATABASE STANDBY CONTROLFILE;
            exit
            EOF
        "
        sleep 1
    fi
}

FN_AUTO_SUCCESS(){
    echo "############################################################"
    echo "# TIBERO_TYPE : $TIBERO_TYPE"
    echo "# TIBERO_NODE : $TIBERO_NODE"
    echo "#  tbis Progress> finaly step done"
    echo "############################################################"
    echo
    echo
}

FN_AUTO_INSTALL(){   
    chmod 655 tbis.log
    TBIS_AUTO_TIME=`date +%F_%T |sed 's/://g' |sed 's/-//g'`
    TBIS_START_TIME=$TBIS_AUTO_TIME
    echo "############################################################"
    echo "# tbis Start Log"
    echo "############################################################"
    echo "# Start time : $TBIS_START_TIME"

    ############# In Progress
    FN_AUTO_INSTALL_CHECK 
    FN_AUTO_ENGINE
    FN_AUTO_TBINARY
    FN_AUTO_PROFILE
    FN_AUTO_TB_SID_TIP
    FN_AUTO_TBDSN
    
    if [ $TIBERO_TYPE == "SINGLE" ]
    then
        FN_AUTO_LICENSE
        FN_AUTO_CHANGE_OWNER
        FN_AUTO_TB_BOOT NOMOUNT
        FN_AUTO_CREATEDB
        FN_AUTO_TB_BOOT NORMAL
        FN_AUTO_SYSTEM_SHELL
    elif [ $TIBERO_TYPE == "TSC" ]
    then
        if [ $TIBERO_NODE == "primary" ]
        then
            FN_AUTO_LICENSE
            FN_AUTO_CM_SID_TIP
            FN_AUTO_CHANGE_OWNER
            FN_AUTO_CM_BOOT
            FN_AUTO_CM_RESOURCE
            FN_AUTO_CHANGE_OWNER
            FN_AUTO_TB_BOOT NOMOUNT
            FN_AUTO_CREATEDB
            FN_AUTO_TB_BOOT NORMAL
            FN_AUTO_SYSTEM_SHELL
            FN_AUTO_TB_DOWN IMMEDIATE
            FN_AUTO_TSC_COPY
        elif [ $TIBERO_NODE == "standby" ]
        then
            FN_AUTO_LICENSE
            FN_AUTO_CM_SID_TIP
            FN_AUTO_CHANGE_OWNER
            FN_AUTO_CM_BOOT
            FN_AUTO_CM_RESOURCE
            FN_AUTO_TB_BOOT MOUNT
            FN_AUTO_TSC_CFG
            FN_AUTO_TB_DOWN IMMEDIATE
            echo
        elif [ $TIBERO_NODE == "observer" ]
        then
            FN_AUTO_CM_SID_TIP
            FN_AUTO_CHANGE_OWNER
            FN_AUTO_CM_BOOT
        fi
    elif [ $TIBERO_TYPE == "TAC" ]
    then
        FN_AUTO_LICENSE
        FN_AUTO_CM_SID_TIP
        FN_AUTO_CHANGE_OWNER
        FN_AUTO_CM_BOOT
        FN_AUTO_CM_RESOURCE
        FN_AUTO_CHANGE_OWNER
        FN_AUTO_TB_BOOT
        FN_AUTO_SYSTEM_SHELL
    fi
    FN_AUTO_SUCCESS
    
    TBIS_AUTO_TIME=`date +%F_%T |sed 's/://g' |sed 's/-//g'`
    TBIS_END_TIME=$TBIS_AUTO_TIME
    echo "############################################################"
    echo "# tbis END Log"
    echo "############################################################"
    echo "# End time : $TBIS_END_TIME"
    ############
}

FN_AUTO_CFG(){
    echo " -----------------------------------------------------------------------------------"
    echo "  1.TIBERO USER CREATE                      |  2.TIBERO User Profile                  "
    echo " ---------------------------------------- + ----------------------------------------"
    echo "  # 11 - MANUAL                             |  # 21 - MANUAL                            "
    echo "                                            |                                         "
    echo " -----------------------------------------------------------------------------------"
    echo "  3.TIBERO Directory                        |  4.TIBERO TIP                           "
    echo " ---------------------------------------- + ----------------------------------------"
    echo "  # 31 - MANUAL                             |  # 41 - MANUAL                            "
    echo "                                            |                                         "
    echo " -----------------------------------------------------------------------------------"
    echo "  5.TIBERO CREATE DATABASE                  |  6.TIBERO CM Resource                   "
    echo " ---------------------------------------- + ----------------------------------------"
    echo "  # 51 - MANUAL                             |  # 61 - MANUAL                            "
    echo "                                            |                                         "
    echo " -----------------------------------------------------------------------------------"
    echo "  c  - Clear terminal                                                               "
    echo "  r  - retry main menu                                                              "
    echo "  press other key to quit                                                                  "
    echo " -----------------------------------------------------------------------------------"
    printf " Choose the Number or Command : "
    read INPUT_NUMBER
}


FN_MAIN_MENU(){
    clear
    echo "[*] TIBERO Installation Shell Script"
    echo "[*] This script is for TmaxTibero "Daejeon Office" only."
    echo "[*] Supported Version : Tibero 6 FS07 ↑"
    echo "-----------------------------------------------------------------"
    echo "# 1. Auto installation"
    echo "# 2. Auto installation "
    echo "# 3. Auto Configuration Text"
    echo "-----------------------------------------------------------------"
    echo "# chk. System Check"
    echo "# ini. Configurations Initialization"
    echo "# press other key to quit"
    echo "-----------------------------------------------------------------"
    printf "Choose the Number : "
    read INPUT_NUMBER
    case $INPUT_NUMBER in
    1)
        clear
        FN_AUTO_LOGFILE
        FN_AUTO_INSTALL |tee $TBIS_AUTO_LOGFILE
        exit
        ;;
    2)
        echo "2";;
    3)
        while true
        do
            FN_AUTO_CFG
        done;;
    *)
        clear
        echo "tbis message> program quit."
        ;;
    esac
}

############################################################
#
# Program start
############################################################
# run
FN_MAIN_MENU 
#FN_MAIN_MENU