#!/bin/sh
############################################################
#
# Program history
############################################################
# Created by. Daejeon Office
# 2022.03.18 Version : Park Si Hyung, Yoon Jun Su
#

############################################################
#
# Program variables
############################################################
# Configuration file path
TBIS_AUTO_LOGFILE="tbis.log"
TBIS_AUTO_CFGFILE="tbis.cfg"
TBIS_AUTO_SQLFILE="tbis.sql"

############################################################
#
# Function lists
############################################################
FN_AUTO_LOGFILE(){
    TBIS_AUTO_TIME=`date +%F_%T |sed 's/://g' |sed 's/-//g'`

    if [ -f $TBIS_AUTO_LOGFILE ]
    then
        mv $TBIS_AUTO_LOGFILE "$TBIS_AUTO_LOGFILE"_"$TBIS_AUTO_TIME"
    fi

    echo "############### tbis LOG" > $TBIS_AUTO_LOGFILE
    echo $TBIS_AUTO_TIME >> $TBIS_AUTO_LOGFILE
    echo >> $TBIS_AUTO_LOGFILE
    echo >> $TBIS_AUTO_LOGFILE
}

FN_AUTO_PROGRESS_CHECK(){
    echo
    printf "continue ? ( [Y]es / [N]o / [S]kip ) : "
    read INPUT_YESNO
    case $INPUT_YESNO in
        "YES"|"Yes"|"yes"|"y"|"Y")
            YESNO=YES
            break;;
        "NO"|"No"|"no"|"n"|"N")
            exit;;
        "SKIP"|"Skip"|"S"|"s")
            YESNO=SKIP
            break;;
    esac
    echo
}

FN_AUTO_ENGINE(){    
    # Engine install
    if [ $TIBERO_ENGINE == "Y" ] || [ $TIBERO_ENGINE == "y" ]
    then
        echo
        echo "############################################################"
        echo "# tbis Progress> Engine"
        echo "############################################################"
        echo
        echo "tar -xvzf ../binary/tibero*.tar.gz -C $USER_HOME"
        echo
        FN_AUTO_PROGRESS_CHECK
        
        tar -xvzf ../binary/tibero*.tar.gz -C $USER_HOME
        
    fi
    
}


FN_AUTO_TBINARY(){
    if [ $TIBERO_TBINARY == "Y" ] || [ $TIBERO_TBINARY == "y" ]
    then
        echo
        echo "############################################################"
        echo "# tbis Progress> tbinary"
        echo "############################################################"
        echo
        echo "tar -xvf ../binary/tbinary*.tar -C $USER_HOME"
        echo
        FN_AUTO_PROGRESS_CHECK
        tar -xvf ../binary/tbinary*.tar -C $USER_HOME
    fi
}

FN_AUTO_PROFILE()
{
    echo
    echo "############################################################"
    echo "# tbis Progress> Profile " 
    echo "############################################################"
    echo
    #TIBERO_BASHPROFILE=`ls  $USER_HOME/.bash_profile |grep -v "^$" |head -n 1 `
    TIBERO_BASHPROFILE=$USER_HOME/.bash_profile
    #TIBERO_PROFILE=`cat $USER_HOME/.profile |grep -v "^$" |head -n 1 `
    TIBERO_PROFILE=$USER_HOME/.profile
    
    FN_AUTO_PROGRESS_CHECK

    if [ -z $TIBERO_PROFILE ]
    then   
        sh tbis.cfg USER_PROFILE >> $USER_HOME/.bash_profile
    elif [ -z $TIBERO_BASHPROFILE ]
    then
        sh tbis.cfg USER_PROFILE >> $USER_HOME/.profile
    fi
}

FN_AUTO_LICENSE(){
    if [ -z $TIBERO_LICENSE ]
    then
        echo
        echo "# tbis Error>../binary/license.xml file"
        echo
        FN_AUTO_PROGRESS_CHECK
    else
        echo
        echo "############################################################"
        echo "# tbis Progress> license apply "    
        echo "############################################################"
        echo
        echo "cp ../binary/license.xml $TB_HOME/license/license.xml"
        echo
        FN_AUTO_PROGRESS_CHECK
        
        cp ../binary/license.xml $TB_HOME/license/license.xml   
        
    fi
}

FN_AUTO_TB_SID_TIP(){
    echo
    echo "############################################################"
    echo "# tbis Progress> TB_SID TIP File Apply Create"
    echo "############################################################"
    echo
    echo "sh tbis.cfg TB_SID_TIP > $TB_HOME/config/$TB_SID.tip"
    echo
    FN_AUTO_PROGRESS_CHECK
    sh tbis.cfg TB_SID_TIP > $TB_HOME/config/$TB_SID.tip
    
}

FN_AUTO_CM_SID_TIP(){
    echo
    echo "############################################################"
    echo "# tbis Progress> CM_SID TIP File Apply Create"
    echo "############################################################"
    echo
    echo "sh tbis.cfg CM_SID_TIP > $TB_HOME/config/$TIBERO_NODE.tip"
    echo
    FN_AUTO_PROGRESS_CHECK
    sh tbis.cfg CM_SID_TIP > $TB_HOME/config/$TIBERO_NODE.tip
    
}

FN_AUTO_SINGLE(){
    export TB_SID=`echo $DB_NAME`
}

FN_AUTO_TSC(){
    export TB_SID=`echo "$DB_NAME"_p`
    export TB_SID=`echo "$DB_NAME"_s`
}

FN_AUTO_TAC(){
    export TB_SID=`echo "$DB_NAME"0`
    export TB_SID=`echo "$DB_NAME"1`
}


FN_AUTO_CREATEDB(){
    echo
}



FN_AUTO_INSTALL(){
    . ./tbis.cfg
    TIBERO_LICENSE=`cat ../binary/license.xml |grep license |head -n 1 `
    echo "[*] TIBERO Auto installation Tools Configuration Checking STEP"
    echo "-----------------------------------------------------------------"
    echo "# System Check"
    echo "- OS USER : $USER_NAME"
    echo "- OS USER GROUP : $USER_GROUP"
    echo "- OS HOME : $USER_HOME"
    echo "-----------------------------------------------------------------"
    echo "# TIBERO Binary"
    if [ -n $TIBERO_ENGINE ]
    then
        echo "- engine : $TB_HOME"
    fi  

    if [ -n $TIBERO_TBINARY ]
    then
        echo "- tbinary : $TB_HOME/tbinary"
    fi
    echo "-----------------------------------------------------------------"
    echo "# TIBERO DATABASE"
    if [ $TIBERO_TYPE == "SINGLE" ]
    then
        echo "- TIBERO TYPE : SINGLE"
        FN_AUTO_SINGLE
    elif [ $TIBERO_TYPE == "TSC" ]
    then
        echo "- TIBERO TYPE : TSC"
        echo "- TIBERO NODE : $TIBERO_NODE"
        FN_AUTO_TSC
    elif [ $TIBERO_TYPE == "TAC" ]
    then
        echo "- TIBERO TYPE : TAC"
        echo "- TIBERO NODE : $TIBERO_NODE"
        FN_AUTO_TAC
    fi
    echo "- TB_SID : $TB_SID"
    echo "- CM_SID : $TIBERO_NODE"
    echo "- CHARSET : $CHARSET"
    echo "-----------------------------------------------------------------"
    echo "# TIBERO Configuration Files"
    echo "- cat tbis.cfg : TIBERO Total Configuration File"
    echo "- cat tbis.sql : CREATE DATABASE SQL File"
    echo "-----------------------------------------------------------------"
    
    FN_AUTO_PROGRESS_CHECK
    
    if [ -z $USER_HOME  ]
    then
        echo " tbis Error> User home checking "
        exit
    fi
  
  
    FN_AUTO_ENGINE
    FN_AUTO_TBINARY
    FN_AUTO_LICENSE
    FN_AUTO_PROFILE
    FN_AUTO_TB_SID_TIP
    FN_AUTO_CM_SID_TIP

    # Owner Change Files
    # chwon -R $USER:$USER $USER_HOME

}

FN_MAIN_MENU(){
    clear
    echo "[*] TIBERO Installation Shell Script"
    echo "[*] This script is for TmaxTibero "Daejeon Office" only."
    echo "[*] Supported Version : Tibero 6 FS07 ↑"
    echo "-----------------------------------------------------------------"
    echo "# 1. Auto installation"
    echo "-----------------------------------------------------------------"
    echo "# chk. System Check"
    echo "# ini. Configurations Initialization"
    echo "# press other key to quit"
    echo "-----------------------------------------------------------------"
    printf "Choose the Number : "
    read INPUT_NUMBER
    case $INPUT_NUMBER in
    1)
        clear
        FN_AUTO_LOGFILE
        FN_AUTO_INSTALL |tee $TBIS_AUTO_LOGFILE
    ;;
    2)
        echo "2"
    ;;
    3)
        echo "3"
    ;;
    *)
        clear
        echo "tbis exit."
        exit
    ;;
    esac
}

############################################################
#
# Program start
############################################################
# run
FN_MAIN_MENU 
#FN_MAIN_MENU