#!/bin/bash

#--------------------------------------------------------------------------------
# Version : 230217
#--------------------------------------------------------------------------------
 

#
#--------------------------------------------------------------------------------
function fn_error_check(){
	# if [ -z "$main_option1" ] || [ -z "$main_option2" ]
	# then
	# 	fn_help_message
	# fi

	if [ -f $current_path/DBDeployer ]
	then
		2>/dev/null
	else
		echo "  error> working path check"
		exit
	fi
}
#--------------------------------------------------------------------------------


#
#--------------------------------------------------------------------------------
function fn_help_message(){
	echo ""
	echo "[*] DBDeployer shell script"
	echo "-----------------------------------------------------------------"
	echo " usage: ./DBDeployer [option1] [option2]"
	echo "-----------------------------------------------------------------"
	echo " option1"
	echo "	tibero		: tibero installation"
	echo "	cubrid		: cubrid installation"
	echo "-----------------------------------------------------------------"
	echo " option2"
	echo "	run 		: start DBDeployer shell script"
	echo "	auto		: automatic mode (or docker build)"
	echo "-----------------------------------------------------------------"
	echo ""
}
#--------------------------------------------------------------------------------


#
#--------------------------------------------------------------------------------
main_option1=$1
main_option2=$2
export current_path=`pwd`
fn_error_check

case $main_option1 in
	"tibero"|"TIBERO")
		main_option1_value="tibero"
			if [ "$main_option2" == "run" ]
			then
				export mode="run"
				. $current_path/lib/tibero/main.sh
			elif [ "$main_option2" == "auto" ]
			then
				export mode="auto"
				. $current_path/lib/tibero/main.sh
			else
				fn_help_message
			fi
		;;
	"cubrid"|"CUBRID")
		main_option1_value="cubrid"
			if [ "$main_option2" == "run" ]
			then
				export mode="run"
			elif [ "$main_option2" == "auto" ]
			then
				export mode="auto"
			else
				fn_help_message
			fi
		;;
	*)
		fn_help_message
		;;	
esac
#--------------------------------------------------------------------------------