#!/bin/bash

#--------------------------------------------------------------------------------
# Version : 1.0
#--------------------------------------------------------------------------------
 

#
#--------------------------------------------------------------------------------
function fn_error_check(){
	# if [ -z "$main_option1" ] || [ -z "$main_option2" ]
	# then
	# 	fn_help_message
	# fi

	if [ -f $current_path/DBDeployer ]
	then
		2>/dev/null
	else
		echo "  error> working path check"
		exit
	fi
}
#--------------------------------------------------------------------------------


#
#--------------------------------------------------------------------------------
function fn_help_message(){
	echo ""
	echo "[*] DBDeployer shell script"
	echo "-----------------------------------------------------------------"
	echo " usage: ./DBDeployer [option1] [option2]"
	echo "-----------------------------------------------------------------"
	echo " option1"
	echo "	tibero		: tibero installation 		(Supported on version 6   or higher)"
	# echo "	cubrid		: cubrid installation 		(Supported on version 8   or higher)"
	# echo "	mysql		: mysql installation		(Supported on version 8.0 or higher)"
	# echo "	postgres	: postgres installation		(Supported on version 13  or higher)"
	echo "-----------------------------------------------------------------"
	echo " option2"
	echo "	run 		: start DBDeployer shell script"
	echo "	auto		: automatic mode"
	echo "  docker		: automatic container run mode (from docker)"
	echo "-----------------------------------------------------------------"
	echo ""
}
#--------------------------------------------------------------------------------


#
#--------------------------------------------------------------------------------
main_option1=$1
main_option2=$2
export current_path=`pwd`
fn_error_check

case $main_option1 in
	"tibero"|"TIBERO")
		main_option1_value="tibero"
			if [ "$main_option2" == "run" ]
			then
				export mode="run"
				. $current_path/lib/tibero/main.sh
			elif [ "$main_option2" == "auto" ]
			then
				export mode="auto"
				. $current_path/lib/tibero/main.sh
			elif [ "$main_option2" == "docker" ]
			then
				export mode="auto"
				. $current_path/lib/tibero/main.sh
				export entrypoint="y"

			else
				fn_help_message
			fi
		;;
	"cubrid"|"CUBRID")
		main_option1_value="cubrid"
			if [ "$main_option2" == "run" ]
			then
				export mode="run"
			elif [ "$main_option2" == "auto" ]
			then
				export mode="auto"
			elif [ "$main_option2" == "docker" ]
			then
				export mode="auto"
				export docker="Y"
			else
				fn_help_message
			fi
		;;
	"mysql"|"MYSQL")
		main_option1_value="mysql"
			if [ "$main_option2" == "run" ]
			then
				export mode="run"
			elif [ "$main_option2" == "auto" ]
			then
				export mode="auto"
			elif [ "$main_option2" == "docker" ]
			then
				export mode="auto"
				export docker="Y"
			else
				fn_help_message
			fi
		;;		
	"postgres"|"postgresql")
		main_option1_value="postgres"
			if [ "$main_option2" == "run" ]
			then
				export mode="run"
			elif [ "$main_option2" == "auto" ]
			then
				export mode="auto"
			elif [ "$main_option2" == "docker" ]
			then
				export mode="auto"
				export docker="Y"
			else
				fn_help_message
			fi
		;;				
	*)
		fn_help_message
		;;	
esac
#--------------------------------------------------------------------------------