#!/bin/sh
############################################################
#
# Program history
############################################################
# Created by. Daejeon Office
# 2022.03.18 Version : Park Si Hyung, Yoon Jun Su
# 2022.03.24 Version : Yoon Jun Su
# 2022.03.28 Version : Yoon Jun Su
# 2022.05.16 Version : Yoon Jun Su
# 2022.05.23 Version : Yoon Jun Su

############################################################
# tbis
# Shell configuration
############################################################
# Shell check
TBIS_SHELL_RUN(){
    SHELL_CHECK=`uname -a |grep -i Ubuntu`

    if [ -n "$SHELL_CHECK" ]
    then
        export TBIS_SHELL="bash"
        bash ./tbis.main
        
    else
        export TBIS_SHELL="sh"
        sh ./tbis.main
    fi
}

# Shell  running
case $1 in
    "")
        TBIS_SHELL_RUN;;
    "-bash"|"--bash"|"bash")
        export TBIS_SHELL="bash"
        bash ./tbis.main;;
    "docker")
        export TBIS_MODE="docker"
        export TBIS_SHELL="bash"
        bash ./tbis.main
        ;;
    *)
        echo
        echo "[*] TIBERO Installation Scripts"
        echo "-----------------------------------------------------------------"
        echo "Usage: ./tbis [OPTION]"
        echo "-----------------------------------------------------------------"
        echo "-bash --bash          default: sh"
        echo "-----------------------------------------------------------------"
        echo
esac